# COGS 108 - Data Checkpoint

# Names

- Jungsoo Lee
- Lu Zhang
- Mengyuan Zhang

<a id='research_question'></a>
# Research Question

Is there a relationship between the location of alcohol shops and the amount of alcohol-related car accidents happened in California?

# Setup

In [1]:
## YOUR CODE HERE
import pandas as pd
import matplotlib.pyplot as plt

# Data Cleaning

Describe your data cleaning steps here.

In [2]:
# https://censusreporter.org/data/table/?table=B01001&geo_ids=04000US06,050|04000US06&primary_geo_id=04000US06
population_df = pd.read_csv('data/acs2019_5yr_B01001_05000US06049.csv')

population_df.drop(index=1,columns=['Sex by Age','Unnamed: 2','Unnamed: 3','Unnamed: 4'], inplace=True)
age_column = population_df['B01001']
population_df.dropna(axis=1, inplace=True)
population_df = pd.concat([age_column, population_df], axis=1)
population_df.columns = population_df.iloc[0]
population_df.drop(0, inplace=True)

population_df.reset_index(drop=True)

,NaN,"Alameda County, CA","Alpine County, CA","Amador County, CA","Butte County, CA","Calaveras County, CA","Colusa County, CA","Contra Costa County, CA","Del Norte County, CA","El Dorado County, CA",...,"Sonoma County, CA","Stanislaus County, CA","Sutter County, CA","Tehama County, CA","Trinity County, CA","Tulare County, CA","Tuolumne County, CA","Ventura County, CA","Yolo County, CA","Yuba County, CA"
0,Total:,1656754,1039,38429,225817,45514,21454,1142251,27495,188563,...,499772,543194,96109,63912,12700,461898,54045,847263,217352,76360
1,Male:,814515,554,20640,111735,22663,10994,558502,14745,93922,...,244045,268871,47866,31773,6535,230966,28112,419111,105438,38950
2,Under 5 years,49611,22,796,6395,920,742,33495,884,4431,...,12771,19998,3372,1938,334,19369,1219,25795,6163,3097
3,5 to 9 years,49375,21,730,6941,1253,919,36175,787,5264,...,14417,19923,3668,2209,278,21062,1451,26436,6495,3123
4,10 to 14 years,48777,53,849,5985,977,817,39793,978,5988,...,14430,22568,3725,2351,305,20810,1146,29918,6586,3139
5,15 to 17 years,28149,9,570,4080,825,521,23934,409,3773,...,8967,12746,2185,1241,239,11971,749,17629,4059,1692
6,18 and 19 years,19354,13,448,3864,461,263,13715,225,2089,...,6064,7503,1234,669,165,7066,598,11334,5914,948
7,20 years,10221,0,247,2876,152,177,6830,191,1220,...,3275,4239,419,604,73,3721,342,6440,4062,589
8,21 years,10048,7,183,2938,272,275,6453,86,1101,...,2753,4071,774,402,40,3489,219,5858,2976,452
9,22 to 24 years,30365,21,452,6791,707,293,21039,521,2707,...,8546,10838,2008,867,145,9836,1018,17438,7325,2019
10,25 to 29 years,68560,8,1237,8352,1032,814,36317,1295,5039,...,16942,20519,3560,2093,289,17242,1959,30386,8342,3328
11,30 to 34 years,69852,30,1190,6798,1016,750,36630,1233,4917,...,16411,19380,3221,1921,248,16005,1891,28134,6890,2959
12,35 to 39 years,63787,44,1444,6140,921,647,36957,1216,5612,...,15797,17131,3001,1814,276,15387,1641,26792,7249,2537
13,40 to 44 years,59958,19,1286,6366,1249,649,37785,1044,4704,...,15314,17228,2846,1810,326,13853,1698,25594,5415,2223
14,45 to 49 years,56727,9,1549,5804,1313,632,39616,796,6145,...,15651,16262,2757,1722,393,13106,1542,27615,5718,1974
15,50 to 54 years,54080,34,1491,6195,1477,640,40095,924,6738,...,16411,16142,2927,2029,473,12538,1638,28726,5805,2179
16,55 to 59 years,51870,29,1475,7151,1956,783,39085,978,7875,...,16593,16561,2715,2348,434,11568,2027,29615,5953,2130
17,60 and 61 years,19475,26,715,2692,749,230,14081,442,3095,...,7314,5362,1295,726,278,4833,782,10646,1939,939
18,62 to 64 years,26247,39,1081,4080,1248,341,19161,494,4675,...,10451,7660,1657,1241,472,5766,1534,13604,2857,1185
19,65 and 66 years,15412,41,769,2751,670,262,11153,414,3011,...,6874,5058,1095,747,299,3873,864,9124,1777,754
20,67 to 69 years,20220,11,888,3663,1237,312,15750,378,3914,...,8828,5920,1177,1028,344,4518,1506,10665,2320,909
21,70 to 74 years,25079,69,1414,4843,1790,365,20423,644,4907,...,11140,7899,1477,1666,434,6002,1729,14917,3044,1211
22,75 to 79 years,16781,41,856,3253,1052,291,13489,271,3005,...,6909,5873,1020,1089,363,4183,1041,9890,1756,712
23,80 to 84 years,10771,0,423,1936,799,136,8368,211,2332,...,4247,3158,961,649,186,2425,782,6256,1501,434
24,85 years and over,9796,8,547,1841,587,135,8158,324,1380,...,3940,2832,772,609,141,2343,736,6299,1292,417
25,Female:,842239,485,17789,114082,22851,10460,583749,12750,94641,...,255727,274323,48243,32139,6165,230932,25933,428152,111914,37410
26,Under 5 years,47238,22,731,5989,982,834,31954,648,4239,...,12366,19378,3185,1901,252,18422,1215,24730,6149,2896
27,5 to 9 years,45905,29,683,6780,1115,726,36275,702,4929,...,13313,20684,3470,1780,375,20214,1174,25684,6003,3189
28,10 to 14 years,47993,20,994,5662,1064,826,36721,982,5795,...,14297,20341,3442,2477,210,19793,1252,29383,6740,2473
29,15 to 17 years,26979,25,494,3607,675,457,22856,530,3503,...,8629,11985,2012,1361,173,11517,781,17212,3831,1469
30,18 and 19 years,19583,12,364,4107,341,337,12806,419,1907,...,6183,7099,1102,532,108,6749,424,10851,7205,834
31,20 years,9360,10,101,2352,247,131,5396,81,685,...,2811,3750,520,284,18,3377,143,6194,4488,349
32,21 years,10717,0,118,3087,219,164,6461,81,719,...,2997,3622,590,403,85,3392,311,4896,4500,474
33,22 to 24 years,30417,5,374,6854,456,295,21170,327,3185,...,8639,10823,1777,1043,53,9759,699,17319,7270,1584
34,25 to 29 years,67880,13,837,7440,1029,647,35273,706,4322,...,15614,20108,3427,1965,206,16431,1384,28142,7681,3087
35,30 to 34 years,69727,15,853,6409,1027,677,37055,751,4792,...,15596,18597,3231,1744,281,15815,1320,26253,6701,2819
36,35 to 39 years,65087,42,897,6566,990,699,38243,823,5684,...,16064,17750,3067,1597,483,15134,1368,25897,6565,2668
37,40 to 44 years,59398,43,667,5331,1176,564,40142,635,5100,...,14887,16529,2846,1914,325,13361,1114,26758,6374,1994
38,45 to 49 years,57136,4,926,5888,1202,611,41265,726,6215,...,15592,16552,2788,1809,312,12894,1399,28300,5922,2083
39,50 to 54 years,55083,9,1236,6498,1581,646,41923,804,7084,...,17403,16727,2965,2129,418,12615,1551,29397,6014,2072
40,55 to 59 years,54961,44,1619,7314,2192,683,41148,1209,8619,...,18923,17086,2840,2129,615,12133,2085,29853,5982,2201
41,60 and 61 years,20842,7,561,2928,1031,301,15611,358,3096,...,7891,6596,1270,949,215,4635,839,10881,2305,988
42,62 to 64 years,27966,44,985,4872,1140,281,20909,483,4746,...,11547,7757,1795,1603,393,6504,1705,15925,3478,1292
43,65 and 66 years,17183,29,843,2910,852,303,12774,374,3065,...,7000,4757,949,983,236,4203,889,9857,2039,752
44,67 to 69 years,23858,16,1076,4247,1287,308,18974,453,4180,...,11329,7171,1316,1318,316,4688,1127,12396,2478,1265
45,70 to 74 years,30227,64,1328,5298,1711,320,24158,607,4766,...,12877,10051,1952,1311,438,7072,2049,16819,3746,995
46,75 to 79 years,20301,13,623,3875,1101,291,16052,383,3563,...,8792,6575,1427,1329,373,4759,1326,11760,2319,823
47,80 to 84 years,15396,4,747,2773,642,163,12452,383,1812,...,5701,4990,1107,682,146,3406,884,8747,1806,580
48,85 years and over,19002,15,732,3295,791,196,14131,285,2635,...,7276,5395,1165,896,134,4059,894,10898,2318,523

In [3]:
male = population_df.iloc[8:19] 
female = population_df.iloc[32:43]
drinking_age_population = pd.concat([male, female]).reset_index(drop=True)
drinking_age_population.drop(population_df.columns[0], axis=1, inplace=True)
drinking_age_population = drinking_age_population.astype('int64')
drinking_age_population = drinking_age_population.sum(axis=0)

drinking_age_population.to_frame()

                                  0
0
Alameda County, CA          1030183
Alpine County, CA               492
Amador County, CA             21176
Butte County, CA             126494
Calaveras County, CA          23983
Colusa County, CA             11622
Contra Costa County, CA      666419
Del Norte County, CA          15932
El Dorado County, CA         106170
Fresno County, CA            543419
Glenn County, CA              14894
Humboldt County, CA           79026
Imperial County, CA           98311
Inyo County, CA                9754
Kern County, CA              497053
Kings County, CA              88168
Lake County, CA               34633
Lassen County, CA             20658
Los Angeles County, CA      6123565
Madera County, CA             84603
Marin County, CA             143838
Mariposa County, CA            9508
Mendocino County, CA          47143
Merced County, CA            145828
Modoc County, CA               4587
Mono County, CA                8600
Monterey County, CA          242256
Napa County, CA               79119
Nevada County, CA             53266
Orange County, CA           1883716
Placer County, CA            212824
Plumas County, CA              9904
Riverside County, CA        1351043
Sacramento County, CA        898668
San Benito County, CA         34541
San Bernardino County, CA   1241152
San Diego County, CA        1997005
San Francisco County, CA     602257
San Joaquin County, CA       415175
San Luis Obispo County, CA   155705
San Mateo County, CA         465213
Santa Barbara County, CA     245525
Santa Clara County, CA      1178796
Santa Cruz County, CA        156310
Shasta County, CA             98753
Sierra County, CA              1619
Siskiyou County, CA           22357
Solano County, CA            260536
Sonoma County, CA            287336
Stanislaus County, CA        303301
Sutter County, CA             53357
Tehama County, CA             34258
Trinity County, CA             6760
Tulare County, CA            246296
Tuolumne County, CA           29724
Ventura County, CA           488029
Yolo County, CA              123261
Yuba County, CA               43187

In [4]:
total_population = population_df.drop(population_df.columns[0], axis=1, inplace=True)
total_population = population_df.iloc[0, :]

total_population.to_frame()

                                   2
0
Alameda County, CA           1656754
Alpine County, CA               1039
Amador County, CA              38429
Butte County, CA              225817
Calaveras County, CA           45514
Colusa County, CA              21454
Contra Costa County, CA      1142251
Del Norte County, CA           27495
El Dorado County, CA          188563
Fresno County, CA             984521
Glenn County, CA               27976
Humboldt County, CA           135940
Imperial County, CA           180701
Inyo County, CA                17977
Kern County, CA               887641
Kings County, CA              150691
Lake County, CA                64195
Lassen County, CA              30818
Los Angeles County, CA      10081570
Madera County, CA             155433
Marin County, CA              259943
Mariposa County, CA            17420
Mendocino County, CA           87224
Merced County, CA             271382
Modoc County, CA                8907
Mono County, CA                14310
Monterey County, CA           433410
Napa County, CA               139623
Nevada County, CA              99244
Orange County, CA            3168044
Placer County, CA             385512
Plumas County, CA              18660
Riverside County, CA         2411439
Sacramento County, CA        1524553
San Benito County, CA          60376
San Bernardino County, CA    2149031
San Diego County, CA         3316073
San Francisco County, CA      874961
San Joaquin County, CA        742603
San Luis Obispo County, CA    282165
San Mateo County, CA          767423
Santa Barbara County, CA      444829
Santa Clara County, CA       1927470
Santa Cruz County, CA         273962
Shasta County, CA             179212
Sierra County, CA               3040
Siskiyou County, CA            43468
Solano County, CA             441829
Sonoma County, CA             499772
Stanislaus County, CA         543194
Sutter County, CA              96109
Tehama County, CA              63912
Trinity County, CA             12700
Tulare County, CA             461898
Tuolumne County, CA            54045
Ventura County, CA            847263
Yolo County, CA               217352
Yuba County, CA                76360

In [6]:
# https://www.chp.ca.gov/programs-services/services-information/switrs-internet-statewide-integrated-traffic-records-system/switrs-2017-report
alcohol_involved_crashes = pd.read_csv('data/alcohol_involved_injury_crashes.csv')
alcohol_involved_crashes.set_index('TABLE 5O ALCOHOL INVOLVED INJURY CRASHES BY COUNTY BY MONTH - 2017  ', inplace=True)
alcohol_involved_crashes.drop(alcohol_involved_crashes.index[[0,1,60]], inplace=True)
alcohol_involved_crashes = alcohol_involved_crashes.iloc[:,-1:]

alcohol_involved_crashes

                                                   Unnamed: 13
TABLE 5O ALCOHOL INVOLVED INJURY CRASHES BY COU...
Alameda                                                    660
Alpine                                                       9
Amador                                                      37
Butte                                                      120
Calaveras                                                   50
Colusa                                                      13
Contra Costa                                               424
Del Norte                                                   12
El Dorado                                                  123
Fresno                                                     303
Glenn                                                       21
Humboldt                                                   111
Imperial                                                    42
Inyo                                                         9
Kern                                                       431
Kings                                                       75
Lake                                                        66
Lassen                                                      12
Los Angeles                                              4,749
Madera                                                     101
Marin                                                      115
Mariposa                                                    24
Mendocino                                                   91
Merced                                                     183
Modoc                                                        8
Mono                                                        16
Monterey                                                   237
Napa                                                        90
Nevada                                                      74
Orange                                                   1,287
Placer                                                     130
Plumas                                                      18
Riverside                                                1,139
Sacramento                                                 817
San Benito                                                  31
San Bernardino                                           1,025
San Diego                                                1,653
San Francisco                                              349
San Joaquin                                                405
San Luis Obispo                                            160
San Mateo                                                  291
Santa Barbara                                              242
Santa Clara                                                686
Santa Cruz                                                 192
Shasta                                                     117
Sierra                                                       3
Siskiyou                                                    37
Solano                                                     232
Sonoma                                                     288
Stanislaus                                                 367
Sutter                                                      67
Tehama                                                      46
Trinity                                                     21
Tulare                                                     199
Tuolumne                                                    51
Ventura                                                    376
Yolo                                                       103
Yuba                                                        31